// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Question) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Question) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Answer struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SupName              string   `protobuf:"bytes,2,opt,name=SupName,proto3" json:"SupName,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Answer) GetSupName() string {
	if m != nil {
		return m.SupName
	}
	return ""
}

func (m *Answer) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type NextID struct {
	GeneratedID          int64    `protobuf:"varint,1,opt,name=GeneratedID,proto3" json:"GeneratedID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextID) Reset()         { *m = NextID{} }
func (m *NextID) String() string { return proto.CompactTextString(m) }
func (*NextID) ProtoMessage()    {}
func (*NextID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *NextID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextID.Unmarshal(m, b)
}
func (m *NextID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextID.Marshal(b, m, deterministic)
}
func (m *NextID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextID.Merge(m, src)
}
func (m *NextID) XXX_Size() int {
	return xxx_messageInfo_NextID.Size(m)
}
func (m *NextID) XXX_DiscardUnknown() {
	xxx_messageInfo_NextID.DiscardUnknown(m)
}

var xxx_messageInfo_NextID proto.InternalMessageInfo

func (m *NextID) GetGeneratedID() int64 {
	if m != nil {
		return m.GeneratedID
	}
	return 0
}

func init() {
	proto.RegisterType((*Question)(nil), "message.Question")
	proto.RegisterType((*Answer)(nil), "message.Answer")
	proto.RegisterType((*NextID)(nil), "message.NextID")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xbc, 0xb8,
	0x38, 0x02, 0x4b, 0x53, 0x8b, 0x4b, 0x32, 0xf3, 0xf3, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x3c, 0x5d, 0x84, 0xa4, 0xb8, 0x38, 0x42, 0x8b, 0x53,
	0x8b, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x21,
	0x2e, 0x96, 0x90, 0xd4, 0x8a, 0x12, 0x09, 0x66, 0xb0, 0x38, 0x98, 0xad, 0xe4, 0xc6, 0xc5, 0xe6,
	0x98, 0x57, 0x5c, 0x9e, 0x5a, 0x84, 0x61, 0x92, 0x04, 0x17, 0x7b, 0x70, 0x69, 0x01, 0x92, 0x41,
	0x30, 0x2e, 0x56, 0x73, 0xb4, 0xb8, 0xd8, 0xfc, 0x52, 0x2b, 0x4a, 0x3c, 0x5d, 0x84, 0x14, 0xb8,
	0xb8, 0xdd, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x53, 0xe0, 0x06, 0x22, 0x0b, 0x25, 0xb1,
	0x81, 0xfd, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x31, 0xf4, 0x5e, 0x10, 0xe0, 0x00, 0x00,
	0x00,
}
